stackskills_bootstrap_1/config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  get '/index' => 'index#index'
  get '/about' => 'pages#about'
  get '/services' => 'pages#services'
  get '/contact' => 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

stackskills_bootstrap_1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

stackskills_bootstrap_1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

stackskills_bootstrap_1/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

stackskills_bootstrap_1/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def services
  end

  def contact
  end
end

stackskills_bootstrap_1/app/helpers/application_helper.rb
module ApplicationHelper
end

stackskills_bootstrap_1/app/helpers/index_helper.rb
module IndexHelper
end

stackskills_bootstrap_1/app/helpers/pages_helper.rb
module PagesHelper
end

stackskills_bootstrap_1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core CSS -->
    <!-- bootstrap-sprockets imports this and importing twice breaks bootstrap (application.css.scss) -->
    <!-- <link href="assets/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom CSS -->
    <link href="assets/modern-business.css" rel="stylesheet">

    <!-- fontawesome maxcdn -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- fontawesome CDN -->
    <script src="https://use.fontawesome.com/e37012ae75.js"></script>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand" href="index.html">Start Bootstrap</a> -->
                <%= link_to "Start Bootstrap", root_path, :class => "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!-- ex: link_to "Delete Article", article_path(@article) -->
                        <%= link_to "About", about_path %>    
                    </li>
                    <li>
                        <%= link_to "Services", services_path %>
                    </li>
                    <li>
                        <%= link_to "Contact", contact_path %>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="full-width.html">Full Width Page</a>
                            </li>
                            <li>
                                <a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="404.html">404</a>
                            </li>
                            <li>
                                <a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <%= yield %>

    <!-- Footer -->

    <hr>

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <!-- bootstrap-sprockets imports this and importing twice breaks bootstrap -->
    <!-- <script src="assets/bootstrap.min.js"></script> -->

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

  </body>
</html>

stackskills_bootstrap_1/app/views/pages/_breadcrumb.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= yield :title %>
            <small>Subheading</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="index.html">Home</a>
            </li>
            <li class="active"><%= yield :title %></li>
        </ol>
    </div>
</div>
<!-- /.row -->

stackskills_bootstrap_1/app/views/pages/about.html.erb
<% provide(:title, "About") %> 

<!-- Page Content -->
<div class="container">
	<%= render partial: "pages/breadcrumb" %>


<!-- Intro Content -->
<div class="row">
    <div class="col-md-6">
        <img class="img-responsive" src="http://placehold.it/750x450" alt="">
    </div>
    <div class="col-md-6">
        <h2>About Modern Business</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
    </div>
</div>
<!-- /.row -->

<!-- Team Members -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Team</h2>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 text-center">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
            <div class="caption">
                <h3>John Smith<br>
                    <small>Job Title</small>
                </h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                <ul class="list-inline">
                    <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

<!-- Our Customers -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Customers</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
    </div>
</div>
<!-- /.row -->

stackskills_bootstrap_1/app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>

<!-- Page Content -->
<div class="container">

    <%= render partial: "pages/breadcrumb" %> 

    <!-- Content Row -->
    <div class="row">
        <!-- Map Column -->
        <div class="col-md-8">
            <!-- Embedded Google Map -->
            <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
        </div>
        <!-- Contact Details Column -->
        <div class="col-md-4">
            <h3>Contact Details</h3>
            <p>
                3481 Melrose Place<br>Beverly Hills, CA 90210<br>
            </p>
            <p><i class="fa fa-phone"></i> 
                <abbr title="Phone">P</abbr>: (123) 456-7890</p>
            <p><i class="fa fa-envelope-o"></i> 
                <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">name@example.com</a>
            </p>
            <p><i class="fa fa-clock-o"></i> 
                <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
            <ul class="list-unstyled list-inline list-social-icons">
                <li>
                    <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <!-- /.row -->

    <!-- Contact Form -->
    <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <div class="row">
        <div class="col-md-8">
            <h3>Send us a Message</h3>
            <form name="sentMessage" id="contactForm" novalidate>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Full Name:</label>
                        <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                        <p class="help-block"></p>
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Phone Number:</label>
                        <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Email Address:</label>
                        <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                    </div>
                </div>
                <div class="control-group form-group">
                    <div class="controls">
                        <label>Message:</label>
                        <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                    </div>
                </div>
                <div id="success"></div>
                <!-- For success/fail messages -->
                <button type="submit" class="btn btn-primary">Send Message</button>
            </form>
        </div>

    </div>
    <!-- /.row -->